BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "cache" (
	"key"	varchar NOT NULL,
	"value"	text NOT NULL,
	"expiration"	integer NOT NULL,
	PRIMARY KEY("key")
);
CREATE TABLE IF NOT EXISTS "cache_locks" (
	"key"	varchar NOT NULL,
	"owner"	varchar NOT NULL,
	"expiration"	integer NOT NULL,
	PRIMARY KEY("key")
);
CREATE TABLE IF NOT EXISTS "categories" (
	"id"	integer NOT NULL,
	"title"	varchar NOT NULL,
	"slug"	varchar NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "failed_jobs" (
	"id"	integer NOT NULL,
	"uuid"	varchar NOT NULL,
	"connection"	varchar NOT NULL,
	"queue"	varchar NOT NULL,
	"payload"	text NOT NULL,
	"exception"	text NOT NULL,
	"failed_at"	datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "job_batches" (
	"id"	varchar NOT NULL,
	"name"	varchar NOT NULL,
	"total_jobs"	integer NOT NULL,
	"pending_jobs"	integer NOT NULL,
	"failed_jobs"	integer NOT NULL,
	"failed_job_ids"	text NOT NULL,
	"options"	text,
	"cancelled_at"	integer,
	"created_at"	integer NOT NULL,
	"finished_at"	integer,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "jobs" (
	"id"	integer NOT NULL,
	"queue"	varchar NOT NULL,
	"payload"	text NOT NULL,
	"attempts"	integer NOT NULL,
	"reserved_at"	integer,
	"available_at"	integer NOT NULL,
	"created_at"	integer NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "migrations" (
	"id"	integer NOT NULL,
	"migration"	varchar NOT NULL,
	"batch"	integer NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "password_reset_tokens" (
	"email"	varchar NOT NULL,
	"token"	varchar NOT NULL,
	"created_at"	datetime,
	PRIMARY KEY("email")
);
CREATE TABLE IF NOT EXISTS "posts" (
	"id"	integer NOT NULL,
	"title"	varchar NOT NULL,
	"slug"	varchar NOT NULL,
	"description"	text,
	"content"	text,
	"image"	varchar,
	"posted"	varchar NOT NULL DEFAULT 'not' CHECK("posted" IN ('yes', 'not')),
	"created_at"	datetime,
	"updated_at"	datetime,
	"category_id"	integer NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("category_id") REFERENCES "categories"("id") on delete cascade
);
CREATE TABLE IF NOT EXISTS "sessions" (
	"id"	varchar NOT NULL,
	"user_id"	integer,
	"ip_address"	varchar,
	"user_agent"	text,
	"payload"	text NOT NULL,
	"last_activity"	integer NOT NULL,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "users" (
	"id"	integer NOT NULL,
	"name"	varchar NOT NULL,
	"email"	varchar NOT NULL,
	"email_verified_at"	datetime,
	"password"	varchar NOT NULL,
	"remember_token"	varchar,
	"created_at"	datetime,
	"updated_at"	datetime,
	PRIMARY KEY("id" AUTOINCREMENT)
);
INSERT INTO "categories" VALUES (1,'new title 0','category-0');
INSERT INTO "categories" VALUES (2,'new title 1','category-1');
INSERT INTO "categories" VALUES (3,'new title 2','category-2');
INSERT INTO "categories" VALUES (4,'new title 3','category-3');
INSERT INTO "categories" VALUES (5,'new title 4','category-4');
INSERT INTO "categories" VALUES (6,'new title 5','category-5');
INSERT INTO "categories" VALUES (7,'new title 6','category-6');
INSERT INTO "categories" VALUES (8,'new title 7','category-7');
INSERT INTO "categories" VALUES (9,'new title 8','category-8');
INSERT INTO "categories" VALUES (10,'new title 9','category-9');
INSERT INTO "categories" VALUES (11,'new title 10','category-10');
INSERT INTO "categories" VALUES (12,'new title 11','category-11');
INSERT INTO "categories" VALUES (13,'new title 12','category-12');
INSERT INTO "categories" VALUES (14,'new title 13','category-13');
INSERT INTO "categories" VALUES (15,'new title 14','category-14');
INSERT INTO "categories" VALUES (16,'new title 15','category-15');
INSERT INTO "categories" VALUES (17,'new title 16','category-16');
INSERT INTO "categories" VALUES (18,'new title 17','category-17');
INSERT INTO "categories" VALUES (19,'new title 18','category-18');
INSERT INTO "categories" VALUES (20,'new title 19','category-19');
INSERT INTO "migrations" VALUES (1,'0001_01_01_000000_create_users_table',1);
INSERT INTO "migrations" VALUES (2,'0001_01_01_000001_create_cache_table',1);
INSERT INTO "migrations" VALUES (3,'0001_01_01_000002_create_jobs_table',1);
INSERT INTO "migrations" VALUES (5,'2026_05_22_175319_create_categories_table',2);
INSERT INTO "migrations" VALUES (7,'2026_05_23_153540_create_posts_table',3);
INSERT INTO "posts" VALUES (1,'Dean Barrows','dean-barrows','Et sed repudiandae ipsa et sit. Aut et rerum voluptatem qui. Nihil sint quas saepe laborum ab veniam tempore distinctio. Mollitia officia voluptates minus. Commodi dolorem eum molestiae veritatis.','Animi voluptatum qui libero voluptatem soluta. Temporibus et a aut est. Vero suscipit eligendi laboriosam explicabo ullam exercitationem consequatur. Aut doloribus nostrum odio et qui. Saepe quidem rem sit ipsa voluptatem temporibus et. Commodi eligendi sed illum sit suscipit at quia. Enim animi illum aspernatur nemo ut expedita debitis. Id est quo perspiciatis. Eveniet voluptatem quaerat non odio quia debitis a. Ex et veritatis a qui. Dolorum consequuntur et autem et sit consequatur sed. Sapiente omnis saepe suscipit est. Rerum molestiae et numquam odit nostrum aut qui. Et accusantium recusandae ipsa corporis. Dolor ullam et porro voluptas nesciunt est. Aut cupiditate itaque doloremque voluptatum. Quod est dolore enim a dolore. Minima earum ipsa velit eligendi odio labore ipsam. Ut provident dignissimos debitis in eligendi. Ut repellendus consequatur sit. Eveniet quo cupiditate doloremque.','https://via.placeholder.com/640x480.png/00bb44?text=debitis','yes','2026-05-27 22:30:27','2026-05-27 22:30:27',1);
INSERT INTO "posts" VALUES (2,'Allison Dietrich','allison-dietrich','Sed ullam et itaque et sunt et. Repellat ut consequatur aut hic nostrum. Asperiores sed amet excepturi hic. Quos voluptas ipsum sed molestiae aut non aperiam. Eaque voluptatem ut explicabo id et.','Porro non voluptas molestiae quae placeat. Maiores sit repellendus autem nobis. Voluptatem molestiae mollitia non harum. Ipsam blanditiis libero animi eum soluta libero. Eaque vitae iste tenetur error et natus aut. Vel aut iure perspiciatis accusamus. Ut fugit cupiditate sed minima. Qui dolorem autem aperiam esse sunt similique voluptate. Natus consequatur rerum qui quia. Et et consectetur expedita dolore illo. Molestiae necessitatibus rerum rerum sint non ducimus molestias. Corporis officiis fugiat neque quis eligendi nisi rerum autem. Culpa excepturi eaque eligendi iste.','https://via.placeholder.com/640x480.png/0011ff?text=repellendus','yes','2026-05-27 22:30:27','2026-05-27 22:30:27',3);
INSERT INTO "posts" VALUES (3,'Kody Hayes','kody-hayes','Laborum cupiditate quo modi voluptatem. Nihil ipsam omnis est sit. Culpa nam et facere illum tempora. Id adipisci cum sequi tempora inventore ullam. Facilis aut quia voluptatibus quis voluptas. Et fuga id omnis quis.','Fugit asperiores adipisci deleniti velit cupiditate et. Earum maxime voluptates nihil. Voluptate repellat illum expedita laudantium. Recusandae sint sunt eos alias. Ipsa non omnis laboriosam itaque sed est. Minus doloribus mollitia quasi et aperiam sed. Ratione quo illo qui qui. Tempora quibusdam qui voluptatem officiis voluptatem magnam ex. Velit nesciunt veritatis autem veniam ut. Nihil ut ut velit tempora laboriosam sit numquam. Repellendus recusandae eos ducimus et repudiandae. Porro minus tempore quis natus qui. Qui distinctio et assumenda doloribus hic iusto libero. Consectetur ut deleniti a repudiandae accusamus eveniet non. Perferendis cumque mollitia eos unde autem. Cumque laborum voluptatum aliquam quae error delectus. Nisi veniam doloribus omnis laboriosam. Enim aliquid rem rerum ullam illum. Mollitia nisi quia omnis. Ut consequatur consequatur maxime omnis quia quos explicabo. Voluptatem quis nemo quos placeat necessitatibus. Perferendis alias omnis vitae a autem eaque velit odit.','https://via.placeholder.com/640x480.png/00aa55?text=similique','not','2026-05-27 22:30:27','2026-05-27 22:30:27',1);
INSERT INTO "posts" VALUES (4,'Mr. Richard Simonis III','mr-richard-simonis-iii','Qui officiis consequatur dolores quae nisi. Reiciendis voluptatem et id odit iure. Aperiam cum alias culpa qui sit qui.','Laboriosam quas earum perferendis qui consequatur id sint. Non consequuntur optio quisquam molestiae voluptas voluptas doloremque. Impedit eaque officia repellat soluta. Qui quia nihil omnis non in dicta ut. Sapiente omnis assumenda perferendis est temporibus. Ex ut autem sint facere. Soluta dolores corrupti sunt odit. Nesciunt rerum enim inventore aut sit. Fuga enim sed et dolorem aut hic quia hic. Autem quia quis quasi eos magni sit. Repellendus accusamus rerum eum delectus error repellat temporibus. Dolor et cum nostrum voluptas hic. Eligendi libero aut veniam molestiae quam exercitationem. Ut natus rerum voluptatibus. Iure est commodi sed in laboriosam minus. Praesentium distinctio vero numquam vel quos. Voluptates voluptatem voluptates dignissimos hic est id officiis.','https://via.placeholder.com/640x480.png/0066ee?text=molestiae','not','2026-05-27 22:30:27','2026-05-27 22:30:27',1);
INSERT INTO "posts" VALUES (5,'Levi Heaney IV','levi-heaney-iv','Est est non in et. Eum perferendis autem omnis et enim sit nihil. Iusto cumque sint aliquid.','Numquam voluptas et suscipit et dicta. Accusamus autem facere aut. In natus et doloribus earum. Architecto ut aliquid quia similique quo. Blanditiis delectus ipsa quia aut porro. Modi quo ipsum quaerat voluptas ut sit. Deserunt aut sapiente ipsam reiciendis adipisci omnis. Consequatur facilis quasi quis voluptatem quia. In impedit tempora occaecati quisquam. Deserunt reprehenderit consequuntur odit ad. Omnis sit sint quo. Aut voluptatem voluptate iste quo porro. Qui voluptatem quis quasi laboriosam rem sint nostrum. Nihil voluptatum ipsam numquam laudantium laborum et. Ut est non quidem iusto. Repellat qui aut porro et. Hic beatae repellat ducimus nulla officiis. Qui nostrum quod quis sit consequatur non deserunt. Odit nulla et quia consequuntur. Ut ea nobis non assumenda. Exercitationem totam voluptatem ut eos autem exercitationem. Quae aspernatur impedit rerum dolorum veniam. Ut optio voluptate aut qui maxime. Animi ducimus eos ut ut. Qui est repellat atque itaque animi veniam neque non. Ut placeat praesentium quaerat beatae. Laboriosam minus labore veniam esse possimus reiciendis est. Nihil tempora reiciendis earum tempore eveniet. Est facere autem occaecati et aliquid ducimus quaerat.','https://via.placeholder.com/640x480.png/009933?text=esse','yes','2026-05-27 22:30:27','2026-05-27 22:30:27',1);
INSERT INTO "posts" VALUES (6,'Randi Hyatt III','randi-hyatt-iii','Libero sed odit saepe repellendus iusto qui. Non beatae rerum temporibus et ea. Qui rem aperiam cupiditate tempore quibusdam.','Enim repellat velit veniam eos quia sint. Consequatur fuga aut iure nihil blanditiis quia rem aperiam. Vel natus vero voluptates fugiat ipsam nam. Ut vero et qui magni molestiae exercitationem incidunt minima. Eaque sequi debitis itaque accusantium. Et odio animi consequatur ex animi. Beatae at dolorem similique molestiae cum. Sed nostrum excepturi repellat sunt dolor recusandae quibusdam eos. Tempore inventore autem explicabo consequatur eum. Maxime recusandae ea et placeat laboriosam voluptatem. At odio voluptates id labore error officiis. Iste veniam magnam non enim. Velit qui quibusdam aut distinctio dolorem. Delectus consequatur iste id est consequatur. Non cupiditate impedit molestiae. Explicabo ipsum exercitationem consequatur nemo. Eveniet qui reprehenderit qui. Et facilis quasi sed ea perspiciatis consequatur fugiat corporis. Odit voluptatibus molestias nostrum. Aut velit facere incidunt animi voluptas. Et debitis dolorem voluptas sunt maiores quis et. Dolorum est voluptatem quod veritatis aut rerum assumenda. Et veniam laborum voluptatem aut quaerat amet. Expedita perspiciatis voluptatem ut nostrum itaque.','https://via.placeholder.com/640x480.png/000011?text=quia','yes','2026-05-27 22:30:27','2026-05-27 22:30:27',1);
INSERT INTO "posts" VALUES (7,'Dawson Bednar','dawson-bednar','Non possimus nisi vitae distinctio voluptatibus. Quis veritatis quidem dolore quis. Delectus nemo officiis et sunt quia eos. Nesciunt accusantium quia nisi amet. Laboriosam culpa facilis qui molestiae minima illum.','Minima expedita pariatur necessitatibus soluta magni voluptatibus placeat. Quam officiis praesentium doloribus accusamus. Minima voluptatem impedit et ducimus pariatur. Voluptatem aperiam sit veritatis aperiam voluptatem ut. Quia qui maiores nobis earum cumque adipisci. Possimus magnam veniam pariatur laudantium voluptas quia maxime. Veritatis dolorem rem adipisci. Enim dolore aut velit dolor sunt totam repellat mollitia. Ipsum voluptas nostrum accusamus nobis deleniti. Est accusantium qui necessitatibus molestiae. Pariatur laudantium autem sed et. Et nesciunt dolor numquam autem odit quia. Quo ut id iste ad expedita. Voluptas ipsa tenetur sit atque. Qui est necessitatibus libero occaecati molestiae vel. Rerum eos odit qui voluptatum voluptatem eaque. Optio reiciendis laboriosam modi deserunt quidem unde consequuntur. Accusantium sed sequi aut reprehenderit sint aut sunt. Et unde consectetur porro non assumenda odio. Qui ea ea et nesciunt molestias inventore.','https://via.placeholder.com/640x480.png/003388?text=placeat','yes','2026-05-27 22:30:27','2026-05-27 22:30:27',2);
INSERT INTO "posts" VALUES (8,'Miss Marlene King','miss-marlene-king','Porro iusto iusto ea minus error impedit ab. Dolores nemo harum enim dolore quis qui. Adipisci voluptas et cum impedit totam voluptatem. Nihil eos ab modi aut expedita. Ullam laudantium occaecati eum blanditiis quibusdam magnam pariatur rerum.','Distinctio ut unde est culpa accusantium sunt nesciunt. Nulla rerum qui nisi et nihil quia. Consectetur reprehenderit eaque ad hic cumque. Accusamus sit facilis dolores fugit omnis. Quia quo accusamus earum saepe. Vel libero nulla occaecati laboriosam. Voluptas veritatis occaecati omnis tempora rerum rerum nisi vel. Rerum facere sint atque aut. Sint dolor aut quisquam enim quaerat architecto sunt. Perferendis placeat aut vel commodi veniam vitae. Pariatur cupiditate suscipit qui necessitatibus. Aut ut repellat accusamus. Aspernatur harum reiciendis ut corporis. Et rerum in et cumque atque. Quia et odio non est rerum natus et. Sint accusamus aut illum dolorum voluptate eos quasi. Modi quia inventore autem accusantium consequatur inventore laudantium. Animi nulla in voluptatem vero veritatis pariatur quos. Dolorum voluptatum et tempore perferendis fugiat. Aspernatur molestias quidem dolorem quis ipsa. Dolorum iusto magnam est et et officiis cupiditate recusandae. Repellendus qui earum quo saepe suscipit qui veniam. Beatae recusandae vitae natus sapiente quo sit suscipit. Officia porro sed minus assumenda aliquid labore aut. Fugiat asperiores quidem occaecati autem minus. Excepturi doloribus excepturi ea aliquam. Magnam magnam aliquid provident atque dolore nesciunt voluptas natus.','https://via.placeholder.com/640x480.png/00aa88?text=quam','not','2026-05-27 22:30:27','2026-05-27 22:30:27',2);
INSERT INTO "posts" VALUES (9,'Prof. Connie Wolff','prof-connie-wolff','Officiis commodi consectetur animi sunt nihil. Ullam ad necessitatibus veniam provident quod voluptatem qui. Distinctio qui voluptatibus quas nesciunt et facere.','Eum sit temporibus accusantium accusamus ut. Quasi quasi quia facere esse velit. Dolorem doloribus assumenda ipsum non est autem. Repellendus voluptas omnis voluptatem enim. Fugiat praesentium minus perferendis qui incidunt consequatur. Aut laborum et ipsa ex. Repellat eligendi cum et velit. Totam odio labore non dolor et ipsa. Ut adipisci temporibus eveniet sit nostrum ea quibusdam. Fugit repudiandae ut illum ullam facilis occaecati a ullam. Vel ea tempore occaecati ipsum delectus expedita eos hic. Dolores aut sapiente rerum facere enim suscipit. Consequatur et numquam quas nihil. Omnis quia natus enim expedita ut illo. Laboriosam quo aut et at ipsum et. Modi quisquam est minima dolorem voluptatem. Impedit odit inventore autem sint qui eum eveniet inventore. Consectetur animi modi eum illo rerum odit fugiat. Quidem voluptate harum aut sed dolores.','https://via.placeholder.com/640x480.png/00cc44?text=odit','yes','2026-05-27 22:30:27','2026-05-27 22:30:27',2);
INSERT INTO "posts" VALUES (10,'Carissa Leffler','carissa-leffler','Recusandae optio accusantium nulla ut totam ad. Blanditiis ullam illum iusto et sint. Libero magni sint aut quo odio est. Minima quis voluptatem nam reiciendis quisquam quisquam. Est repellendus excepturi saepe cumque id expedita adipisci ut.','Ut placeat dolor labore et qui sint. Ad et rerum voluptatum sunt recusandae ratione. Non repellendus omnis culpa omnis. Sed expedita suscipit repellendus veritatis perferendis odio. Aut consequatur corporis et earum omnis qui. Quasi nulla blanditiis illo ab rem iste quasi nam. Rerum dicta dicta numquam nisi excepturi reprehenderit repudiandae. Voluptatem minus deserunt exercitationem ea. Ex nam rerum reiciendis. Quia quas alias nulla ratione quo eligendi quos nisi. Repudiandae perferendis qui temporibus et. Velit voluptatem necessitatibus totam aspernatur ipsa magni nostrum. Voluptate consectetur ut soluta molestias quam culpa vitae. Est quibusdam omnis ut cupiditate hic id. Non omnis blanditiis ullam mollitia autem sint id. Est et quasi ut odit. Doloremque eligendi et dignissimos sit qui accusamus. Aut iure corrupti doloribus unde vel voluptatem provident ut. Molestiae non sapiente ad consequatur pariatur quia. Sequi assumenda animi magni.','https://via.placeholder.com/640x480.png/00bbdd?text=saepe','not','2026-05-27 22:30:27','2026-05-27 22:30:27',2);
INSERT INTO "posts" VALUES (11,'Albina Ward','albina-ward','In tenetur ut non odit. Adipisci voluptates aut ad recusandae cupiditate. Ut veritatis deserunt sit error voluptas a animi. Et culpa enim voluptatum illum minima est quia. Vel ut rerum possimus dicta quibusdam ab.','Nisi numquam aperiam et. Saepe aspernatur placeat quibusdam. Aut harum neque eligendi atque. Nobis est aliquam illum tenetur voluptate magni enim. Molestiae accusamus a rem quas. Temporibus perspiciatis cumque in iusto ullam. Quidem consequatur recusandae labore adipisci. Quod velit alias impedit dolor quia totam cupiditate nobis. Harum in minus dolorem eum voluptatem officiis rem. Id est sequi minima in est. Repellat earum ipsum eum nam facere dolore. Facere voluptas eos placeat. Quidem ipsam odio nisi eveniet iure sit ut. Praesentium voluptas similique pariatur dolores atque ea. Id aut qui pariatur voluptas cupiditate harum. Occaecati est praesentium est vero culpa. Reprehenderit in omnis debitis culpa sed sed laudantium. Pariatur sapiente sed voluptatem ab dignissimos dolorem. Ipsa et quia accusamus similique dolorem voluptatibus. Earum sed ipsam in quisquam. Inventore aliquam voluptatem vitae beatae ratione. Aliquam sit temporibus voluptate saepe consequatur eaque ratione vitae. Optio ut accusamus laboriosam est ut cumque. Ut omnis totam magni.','https://via.placeholder.com/640x480.png/007766?text=et','not','2026-05-27 22:30:27','2026-05-27 22:30:27',2);
INSERT INTO "posts" VALUES (12,'Prof. Sage Tromp Jr.','prof-sage-tromp-jr','Nemo reprehenderit minus animi rerum ducimus eveniet aperiam. Earum quae mollitia magni expedita rerum repellat labore et. Labore optio porro fuga modi. Non veniam qui voluptas eaque commodi.','Dolor inventore occaecati magni est et eveniet nemo. Necessitatibus incidunt aliquid sunt saepe sit nihil. Numquam fugiat ex natus doloremque voluptatem. Eum sint pariatur quidem dolor ut. Laboriosam fuga quidem eos non sint placeat ratione. Blanditiis non tempora esse est dolorem dolorem quidem. Earum illo ipsa enim labore. Eum occaecati consequatur et voluptate eos eveniet quidem. Officiis ut nemo soluta ipsa iusto ad. Unde repudiandae accusamus at tempore et ut. Qui quia enim et doloribus nobis. Ut quia sed fugiat porro voluptate odio nesciunt quos. Ut provident atque molestiae quidem nihil. Eaque assumenda similique vel rerum quidem architecto. Sit incidunt et quia at non. Aut blanditiis et dolor ipsam. Consequatur dolor autem nesciunt adipisci sequi reprehenderit esse. Et qui non ipsum dicta ut labore sit.','https://via.placeholder.com/640x480.png/00bb44?text=eveniet','not','2026-05-27 22:30:27','2026-05-27 22:30:27',1);
INSERT INTO "posts" VALUES (13,'Amelie Abernathy','amelie-abernathy','Repellendus eaque dolorem expedita numquam dolore voluptas cupiditate. Debitis quas qui dolorem soluta quasi exercitationem. Dolorum dolorum repellendus exercitationem eos. Delectus non impedit sunt nisi. Illo qui animi cupiditate dolorem necessitatibus. Quam odit omnis fuga.','Itaque cumque a amet excepturi quisquam aperiam. Non velit quaerat rerum quo. Quia eaque sed et maiores sequi enim. Nihil consequatur consequatur iusto sunt est vitae ea minima. Cumque hic tempore saepe voluptatum est velit. Facilis esse fugit eum rerum ab. Laudantium quia consequuntur a sequi commodi nulla amet eos. Quia et autem eaque ut. Quia numquam illum et quasi dolores quia. Et ex similique eius sapiente quis non et iure. Asperiores repellat maxime sit. Esse veniam qui molestias delectus. Cupiditate ab distinctio placeat expedita veritatis cumque. Tenetur delectus aspernatur non ad nam veritatis. Magnam veritatis qui veniam rerum rem porro earum ut.','https://via.placeholder.com/640x480.png/00ee77?text=qui','not','2026-05-27 22:30:27','2026-05-27 22:30:27',1);
INSERT INTO "posts" VALUES (14,'Marge Sauer V','marge-sauer-v','Fugit omnis quae et. Natus enim sit minus aliquid aut tenetur et. Excepturi qui id ut ut eius.','Deserunt ratione nesciunt fugiat velit. Saepe eos adipisci qui et qui et. Sit voluptatum rerum vel rerum hic explicabo itaque minima. Est quia at deleniti saepe velit consequuntur aliquid earum. Esse perferendis consequatur molestiae quis quia non. Sed et facere porro ut laudantium distinctio qui vel. Voluptas harum nulla odit non. Mollitia nesciunt ut doloremque ratione laudantium dolore. Quis laboriosam sed sit est nisi. Aut nemo reiciendis tempora aperiam molestiae qui. Qui sint cupiditate perferendis quasi quam repudiandae vitae. Ducimus veritatis illum quod fugiat qui. Nihil cumque quae sint eos saepe ut. Est voluptatem iusto exercitationem id facilis. Doloremque reiciendis quasi dolore nemo ipsa molestias debitis. Qui debitis nulla temporibus qui suscipit iusto et modi. Non eum et beatae suscipit tenetur. Accusantium non eos amet rerum nesciunt consectetur. Molestiae quibusdam sit ea perspiciatis itaque non quia. Voluptas veniam aut aut et cupiditate pariatur ad. Ut non sapiente repudiandae modi accusantium totam. Itaque sunt rerum doloremque expedita.','https://via.placeholder.com/640x480.png/002255?text=iure','not','2026-05-27 22:30:27','2026-05-27 22:30:27',3);
INSERT INTO "posts" VALUES (15,'Ms. Chaya Hodkiewicz','ms-chaya-hodkiewicz','Cum fuga magnam quasi atque. Deleniti vel sint ut ab non aliquam quo. Aut eum a rerum quia qui autem vero.','Voluptas ipsam vero ad optio expedita culpa deserunt aspernatur. Occaecati atque autem velit et et. Aut expedita nihil ipsam omnis. Omnis quo et qui aspernatur est. Quo voluptas in repellat ex culpa. Et inventore deleniti et minima. Non voluptas sapiente ut corrupti totam aut ut. Unde optio ex blanditiis consequuntur reiciendis et. Quibusdam tempora aut consequatur consequuntur. Sunt non quis autem rerum dolore sint similique. Est asperiores quia et laboriosam aliquam vel non et. Ut ut voluptatibus quia enim qui. Ea saepe numquam officiis illo non rerum deleniti. Cum illum molestiae adipisci repellendus quos vel. Tempora illum natus rerum laboriosam et reprehenderit aut et. Cum temporibus modi facere illum sunt doloremque. Voluptatem temporibus numquam ab. Totam consequatur assumenda eum. Voluptatem quod et harum velit est. Rerum dolore earum repudiandae non veniam sapiente. Eius commodi cupiditate odit veniam. Quis est voluptatibus id.','https://via.placeholder.com/640x480.png/0000aa?text=ad','not','2026-05-27 22:30:27','2026-05-27 22:30:27',1);
INSERT INTO "posts" VALUES (16,'Dr. Isai Metz','dr-isai-metz','Reprehenderit beatae enim necessitatibus omnis molestias fuga deleniti. Ex et aut molestias assumenda consequuntur consequatur quia. Ipsum ut et distinctio enim sed.','Est consequatur quis et voluptates molestiae magni. Et autem voluptas qui facilis quia alias est. Enim voluptates quo eaque laborum facere enim. Aut reprehenderit in et consequatur. Iure ut neque quo repellendus. Harum maxime qui quaerat recusandae magni veritatis dolore eius. Nostrum minima ducimus consectetur voluptatem et. Ea at enim ut aut non itaque eum laboriosam. Sit reprehenderit quia at minima voluptatum occaecati possimus animi. Occaecati qui neque vero enim optio. Tempora quo ab facilis sequi ut amet dolore voluptatibus. Et velit aut praesentium. Quisquam sint perspiciatis repellendus iusto. Sapiente libero dolorem doloremque molestias. Cumque aut non aliquam voluptatem cupiditate. Magnam adipisci deserunt sed vitae impedit minus eaque. Enim inventore praesentium quibusdam accusantium. Aliquam maxime harum qui eum. Soluta dolorum adipisci et qui labore quas cumque. Consequatur sunt et cumque. Neque consectetur quasi sit. Amet rerum assumenda vitae officiis quasi delectus aut numquam.','https://via.placeholder.com/640x480.png/00ee11?text=commodi','yes','2026-05-27 22:30:27','2026-05-27 22:30:27',3);
INSERT INTO "posts" VALUES (17,'Dominic Kub','dominic-kub','Pariatur nostrum aut adipisci impedit quo dolorem. Dolore iusto aut ipsam ratione pariatur laudantium. Eaque saepe nobis quo voluptatem. Repellendus debitis in perspiciatis quia cupiditate in asperiores. Illo culpa ad aperiam et error. Eligendi corrupti non molestiae repellendus cupiditate eligendi.','Enim consequatur aliquam ut consequatur dicta. Vel in suscipit consectetur quia possimus pariatur qui voluptas. Aperiam commodi minus hic neque perferendis. Ipsa accusamus quasi tenetur molestias non totam eveniet quibusdam. Sequi dolores voluptas sunt natus. Esse itaque tenetur eaque illum doloribus. Eum quia ratione molestiae. Odit ipsa doloremque molestiae beatae saepe. Voluptas facere hic sed qui velit. Similique facere libero molestiae explicabo magni temporibus eos. Voluptas consectetur voluptatem aspernatur accusamus quos. Deserunt enim aliquam fugit. Quos impedit delectus vero incidunt fuga rem ratione corporis. Doloribus eveniet deleniti dolor quia illo sit quia.','https://via.placeholder.com/640x480.png/00ff55?text=cum','yes','2026-05-27 22:30:27','2026-05-27 22:30:27',2);
INSERT INTO "posts" VALUES (18,'Maureen Kemmer','maureen-kemmer','Eligendi minima reiciendis omnis modi fuga dolore quod. Blanditiis perferendis esse est vero. Natus eveniet maxime sint sed. Eum in mollitia iusto rerum atque perspiciatis molestiae.','Voluptatem maxime nobis eius. Consequatur odit repellendus est cumque. Numquam sint animi perspiciatis libero. Culpa dolore eum nihil minima soluta expedita aperiam qui. Accusamus vel cum dolorem enim sit. Velit in ad adipisci voluptas expedita. Alias iste architecto libero exercitationem exercitationem. Et iusto laborum fugit unde odio aut illum. Velit dolor est odio ea enim blanditiis accusamus. Ratione earum dolore accusantium. Excepturi aut magnam reprehenderit dolores quia voluptatem. Corporis cum eligendi quia nobis aut sit aut officia. Sit esse qui non rem laudantium nostrum dolores. Quae nobis dolorem itaque iusto nihil autem. Aut hic ea provident repellat sint similique. Blanditiis a quis illum magni nostrum voluptate. Eaque quibusdam ut praesentium pariatur tempora dolorem tempore. Vitae voluptatem aliquid quis ipsam beatae. Rerum quae nihil perspiciatis voluptatem quod rerum est. Sit debitis mollitia quos facere omnis dolores perferendis. Vel assumenda est magnam et esse. Ea voluptatem numquam unde necessitatibus et ad. Id dolore ratione voluptas beatae tempora.','https://via.placeholder.com/640x480.png/00cc00?text=sapiente','yes','2026-05-27 22:30:27','2026-05-27 22:30:27',3);
INSERT INTO "posts" VALUES (19,'Haylie Ankunding','haylie-ankunding','Dolores impedit sed officia natus ipsum atque. Officiis quia libero ex ex explicabo enim eveniet. Dolor dolor enim et earum cum. Sed quam porro quia et. Eos ut laudantium ex architecto ut inventore non. Quas totam impedit aut quia delectus dolor.','Et iure amet amet saepe quis nihil. Sit corrupti ducimus accusantium facilis nam quidem. Voluptatibus reiciendis quo et exercitationem commodi aliquam. Quibusdam assumenda omnis voluptate est. Est aspernatur nam esse doloremque dolorum nostrum porro. Tempore rerum exercitationem eos recusandae ipsam voluptas fugiat. Ut totam iste impedit. Iste ea accusamus sunt dolor saepe. Perspiciatis corporis est saepe asperiores. Rerum sequi necessitatibus maxime est eum. In a soluta dolor est sit expedita. Est et corrupti sit dolor. Dolor nihil veritatis ut ad quam doloribus ratione. Et maiores aliquam dolores aspernatur debitis. Ut quod repudiandae molestias ipsum est. Voluptatibus recusandae magnam nam. Alias labore maiores totam accusamus voluptas accusantium non. Aut accusantium et itaque ut inventore qui amet soluta. Aspernatur eum inventore quas rerum. Tempora debitis dolor harum ut est magni. Quod blanditiis est sequi. Iure delectus aut velit omnis eius omnis dolores. Non consectetur libero soluta tempore necessitatibus exercitationem earum. Repellendus necessitatibus enim consectetur ut.','https://via.placeholder.com/640x480.png/005500?text=vitae','not','2026-05-27 22:30:27','2026-05-27 22:30:27',1);
INSERT INTO "posts" VALUES (20,'Miss Agnes Bailey I','miss-agnes-bailey-i','Pariatur animi tenetur voluptatem qui ad explicabo ut quis. Doloremque quis distinctio dolor omnis aliquid eum. Aut aspernatur vero nulla.','Expedita temporibus aut vero modi. A voluptatem alias neque sint rem est doloremque. Officiis assumenda nostrum similique provident et. Ut architecto qui earum dolorem ducimus. Nisi sint maiores autem rerum libero ut. Qui vero autem ratione consequatur laudantium. Consectetur doloribus harum voluptatem fuga repellat veniam officia voluptas. Qui animi a rerum. Deleniti quos minima autem explicabo eos. Culpa odit aspernatur saepe minus. Natus aliquam unde ad asperiores. Accusamus in quia eaque qui modi et sed iusto. Voluptates placeat nesciunt reprehenderit magni qui quos ut. Odio suscipit voluptas id quibusdam eaque soluta ipsa.','https://via.placeholder.com/640x480.png/0099aa?text=soluta','yes','2026-05-27 22:30:27','2026-05-27 22:30:27',3);
INSERT INTO "posts" VALUES (21,'Jaylen Bruen','jaylen-bruen','Fugit quas dolorem dicta id ut. Et reiciendis assumenda iusto quibusdam dolorum porro facere. Atque pariatur enim inventore fuga non velit modi unde. Alias sapiente dolorum voluptatum temporibus perferendis vitae aut.','Quod debitis enim aut. Vero magnam dolores explicabo dolorem et voluptatem odio. Non eos libero impedit eum quidem incidunt. Ipsum in doloremque voluptatem deserunt dolore voluptas eligendi. Impedit cumque perspiciatis maxime repellat quos voluptates. Eveniet nam neque fugit beatae iusto qui ullam. Laboriosam iure soluta quo vel in culpa. Corporis molestiae nam quis molestias. Repellendus qui excepturi sequi et vel. Ducimus deserunt occaecati impedit omnis cumque quo suscipit eum. Temporibus laboriosam iure qui quibusdam. Ea consequatur non nam ad doloribus animi eveniet. Consequatur repellat ut qui aut. Esse quis ex minima sit voluptate omnis ut. Error reprehenderit nam aliquam quia quia. Consequuntur quis sunt repudiandae blanditiis veniam ipsum. Maxime quam qui consequuntur corrupti asperiores. Corrupti aut quae deleniti autem aut delectus. Provident accusamus beatae ipsa hic sequi aliquid quis. Blanditiis hic asperiores non cumque. Voluptatum ea veritatis eum sint iusto in. Nostrum iusto dolorem et. Corporis soluta commodi animi quibusdam esse facilis ipsum. Incidunt perspiciatis voluptatem consequatur magni minima praesentium. Sint nulla consequuntur rem animi aut nam.','https://via.placeholder.com/640x480.png/00ddaa?text=laudantium','not','2026-05-27 22:30:27','2026-05-27 22:30:27',3);
INSERT INTO "posts" VALUES (22,'Mr. Ricky Runolfsson','mr-ricky-runolfsson','Qui quam non voluptas omnis delectus voluptas et. Maxime autem esse nisi ad. Placeat recusandae quod fuga minus molestiae. Voluptatum natus magni laboriosam dolor.','Rem perspiciatis et accusamus dolorem dolor sit consequatur. Veniam tenetur quos aut omnis accusamus sunt recusandae magnam. Libero incidunt et delectus ratione nihil. Laudantium sed ut error facilis adipisci fugiat soluta. Facere dignissimos ut quod quas. Voluptatem voluptatem delectus est modi reprehenderit. Molestiae alias pariatur sed nihil officia. Eligendi velit quo voluptatem laboriosam molestias perferendis. Saepe distinctio quo et quas consectetur. Officiis omnis sed cumque quod accusantium veniam. Rerum nihil veniam consequatur. Voluptatem omnis reprehenderit nulla ducimus aut. Eaque in possimus tempore illum. Nostrum temporibus corrupti et ut quam corrupti rerum veniam. In minima voluptates ullam consequatur labore. Non alias autem accusamus qui atque. Incidunt nobis doloribus aut. Quod et aut quis aut. Minima molestiae totam eos dolorem dicta eos non harum. Illo sed vitae dignissimos ea occaecati. Quaerat tenetur ut modi occaecati. Eius ut unde facere commodi repellat amet et. Est sint qui quas sit facere aut beatae.','https://via.placeholder.com/640x480.png/001100?text=velit','yes','2026-05-27 22:30:27','2026-05-27 22:30:27',3);
INSERT INTO "posts" VALUES (23,'Cortney Turner','cortney-turner','Laborum officia quia ratione vero voluptate qui. Consequatur temporibus consequatur perferendis id qui. Optio velit dolores harum est aut. Natus reprehenderit fugit voluptate cumque quis et.','Quas consequatur impedit qui voluptatibus vel. Accusamus nulla explicabo consequuntur totam sapiente consequatur dolor deserunt. Et ut voluptatum omnis pariatur omnis ratione. Laboriosam et ipsam culpa doloremque esse sequi. Distinctio autem doloremque laborum. Consectetur praesentium officiis dignissimos porro. Officiis ullam expedita eveniet unde animi dignissimos. Perferendis et voluptate sapiente aliquid eum placeat aut. Recusandae nemo nisi perspiciatis qui dolorem et libero. Consequatur eius corporis voluptate. Cumque magni error et dolores et dolores temporibus. Et nobis fugit ipsum rerum ab adipisci excepturi. Qui ullam et sapiente ut aut amet. Qui tenetur et tempora aut in iusto maxime. Est earum eius provident molestiae neque vel aut.','https://via.placeholder.com/640x480.png/00bb88?text=architecto','yes','2026-05-27 22:30:27','2026-05-27 22:30:27',2);
INSERT INTO "posts" VALUES (24,'Adrienne Kiehn','adrienne-kiehn','Aliquid saepe et voluptatem odio explicabo eius aspernatur. Rerum omnis sequi omnis ipsum accusamus vel. Voluptatum odio non similique est. Nulla modi eos ea est. Et ipsum omnis sit inventore. Et rerum dignissimos totam voluptas tempore sit et.','Qui sunt neque deserunt voluptatem quidem. Vitae aut dicta at ducimus veniam ipsam eligendi. Dolor molestias sit itaque et porro. Impedit voluptas sint commodi suscipit officiis numquam ab. Assumenda atque ut ullam. Quod reprehenderit nihil voluptas et iure voluptatum dolor. Sit est sequi distinctio asperiores aspernatur. Ullam ut et et qui omnis occaecati. Eligendi molestias quidem ea ut. Ratione soluta qui reiciendis autem numquam non ex vero. Et repudiandae et corporis et aperiam distinctio consequatur. Modi eligendi animi rerum deserunt eum accusantium. Laborum excepturi nesciunt ab fuga dolorem et. Occaecati aut omnis vel eaque hic enim sed. Quia numquam sit incidunt. Harum sunt ad omnis ut voluptates nam est. Autem beatae vel ut beatae quis aspernatur quas voluptas. Vel similique culpa non adipisci. Commodi accusantium maiores in eos necessitatibus non dolore. Delectus quo dolor consequuntur illo. Vero corrupti voluptatem possimus qui excepturi consequatur. Dolore qui amet laborum rerum rem. Dolore pariatur voluptas autem. Consequuntur voluptatem aut amet porro sunt ut. Esse quo facilis accusantium corrupti eius iure et. Ea quo earum ut.','https://via.placeholder.com/640x480.png/0000aa?text=libero','not','2026-05-27 22:30:27','2026-05-27 22:30:27',1);
INSERT INTO "posts" VALUES (25,'Ms. Mariela Effertz','ms-mariela-effertz','Dignissimos doloribus voluptas corrupti consectetur rerum. Quos est blanditiis sunt dolores incidunt. Architecto quia quia quos a perspiciatis. Delectus iusto labore ut ullam deleniti.','Possimus laudantium atque eum eum harum deleniti fugiat. Itaque quod qui illo nihil. Adipisci aliquid nobis explicabo odit dolore quo nostrum cum. Natus deleniti laudantium inventore excepturi. Eos ut rerum magnam dolor atque illum. Ea est maxime voluptatem quos. Et provident quia voluptate enim provident. Distinctio commodi expedita modi enim. Autem est vero cumque. Corporis aperiam sequi autem repudiandae. Rerum molestiae corporis odit aliquam saepe sunt et. Porro laudantium perspiciatis debitis quas doloribus id nobis. Corrupti quam qui nulla quia ea. Itaque odit et culpa explicabo ea. Aut ea ea veniam qui. Culpa quasi occaecati sunt sunt dolore expedita omnis. Ipsam aspernatur molestias corrupti sint qui laboriosam. Numquam et necessitatibus aut dolores. Rerum quia dolorem a repudiandae officiis reprehenderit. Dicta recusandae natus unde ut qui. Voluptatem et sed dolor quia. Repellat aut et ut excepturi incidunt.','https://via.placeholder.com/640x480.png/00bb22?text=sunt','yes','2026-05-27 22:30:27','2026-05-27 22:30:27',2);
INSERT INTO "posts" VALUES (26,'Mabelle Durgan','mabelle-durgan','Possimus totam similique vel harum voluptas. Explicabo culpa sint dolore eos. Voluptas ut non eveniet at id eum. Facilis aut ipsum atque nesciunt aut dolor. Animi amet autem sequi tempora et impedit. Quo quia sapiente eius.','Suscipit repudiandae laborum vel iste sit quaerat. Maiores in voluptas quis error itaque magni earum. Deserunt quae nobis voluptates ut itaque. Vel occaecati in natus nulla ipsum sint reprehenderit. Rerum neque odio illo qui ea id. Excepturi consequatur quia molestiae deserunt. Aut et consequatur velit. Doloribus eveniet doloremque eaque. Quas a ducimus quidem. Repellendus error non excepturi aspernatur in. Quia tempore totam eos laboriosam eos. Quasi quibusdam vel eum quia eaque numquam eaque. Cupiditate delectus ratione occaecati. Est nihil aut veniam. Sapiente soluta blanditiis magnam nihil non dolores voluptas dolore. Veritatis eos nesciunt reiciendis ex. Commodi sapiente rem tempore ipsa sunt reprehenderit.','https://via.placeholder.com/640x480.png/0033dd?text=optio','not','2026-05-27 22:30:27','2026-05-27 22:30:27',2);
INSERT INTO "posts" VALUES (27,'Orion Howe','orion-howe','Id rerum ea iusto tenetur omnis aut quisquam. Molestiae perspiciatis deserunt ducimus. Assumenda cupiditate quam architecto provident rem esse. Id dolores doloribus id at ea. Quia nesciunt illum laborum et. Incidunt et ex aliquid ut consequatur.','Molestiae tenetur nam fuga perferendis odit aut. Repellendus perspiciatis in itaque rerum quo. Ab nostrum beatae voluptatem sed est facilis ipsa. Error voluptate quo aut debitis quo amet non. Non debitis quisquam expedita est delectus ut doloremque nihil. Qui et quo qui nisi voluptatem molestiae. Totam nobis molestiae nam nesciunt iure. Eveniet optio voluptatem vel sapiente. Hic corporis omnis ut. Est aut qui suscipit quo nemo et cumque asperiores. Voluptas dolores facilis ea omnis quo aut eos. Et reprehenderit omnis consectetur facere ex aspernatur repudiandae. Non iure deserunt optio reiciendis aperiam. Vero nihil officia in ipsa enim harum numquam. Dolor earum aliquid alias. Minus aspernatur id ea et id. Qui quia deserunt illum iste fugiat quos quo ad. Ullam delectus fuga adipisci officiis dolorum fugiat voluptatum. Voluptatem atque eum officiis fugit provident quidem. Natus a sequi qui est saepe id. Nihil cumque ea quo esse voluptatem delectus consectetur. Distinctio saepe non dolores hic totam animi. Iure dicta consequatur qui sint porro soluta asperiores.','https://via.placeholder.com/640x480.png/002299?text=voluptatibus','not','2026-05-27 22:30:27','2026-05-27 22:30:27',2);
INSERT INTO "posts" VALUES (28,'Neoma Denesik','neoma-denesik','Voluptas quis sint quibusdam earum. Sed ducimus ab ut. Aut velit in dolor sed veniam. Distinctio in et et ut saepe doloribus delectus molestiae. Velit aut est blanditiis et perspiciatis.','Qui fuga et pariatur repudiandae aspernatur id. Consequatur maxime incidunt sed enim nobis expedita occaecati. Ad doloribus quaerat maiores rerum aperiam. Eos et eum non hic. Ipsam numquam eaque quia quidem ut. Est perferendis non placeat magni nihil exercitationem. Cumque perspiciatis veniam veniam aspernatur. Dolorum labore minima ducimus quisquam voluptas. Velit omnis voluptatem necessitatibus qui. Iure libero in reprehenderit enim illo aliquid pariatur. Cum natus accusamus et atque rerum unde. Totam ut voluptates aliquam tenetur. Ipsam blanditiis facere consequatur autem qui velit vero ducimus. Vitae ut iste dolor tempora laborum. Quibusdam autem quisquam earum eaque veniam facilis quidem.','https://via.placeholder.com/640x480.png/00dd33?text=cumque','yes','2026-05-27 22:30:27','2026-05-27 22:30:27',2);
INSERT INTO "posts" VALUES (29,'Molly Morissette','molly-morissette','Numquam sed tempora ea maiores eius dolorem. Eaque delectus et quas ut eum. Velit cupiditate nobis omnis veritatis dolorum labore hic. Dolorem et est labore similique.','Culpa libero non est qui maiores tempore. Enim laborum inventore voluptas rerum ut ut. Consequuntur quia alias ut at nisi. Sed sunt iste quis impedit. Sequi a qui ex eius in. Necessitatibus sit illum aut temporibus tempore quaerat assumenda molestiae. Ullam itaque delectus sunt neque quam rerum eveniet. Numquam non exercitationem unde accusantium consequatur. Sit porro numquam quaerat quo quaerat officiis voluptas officiis. Neque voluptas saepe provident est blanditiis labore qui. Voluptas qui exercitationem veniam vitae culpa tenetur. Rerum esse cumque vitae suscipit necessitatibus. Est eos aut eos eaque quis quasi. Non magni et cumque et fugiat maiores deleniti autem. Soluta explicabo atque quo qui accusantium voluptatem sit. Id cupiditate provident labore occaecati. Voluptas qui animi explicabo sint ratione cumque. Et minus quas nulla ducimus qui doloremque tempore. Atque adipisci dignissimos maiores. Ut numquam voluptas adipisci nesciunt et est. Consectetur deleniti qui eum minus.','https://via.placeholder.com/640x480.png/001111?text=eius','yes','2026-05-27 22:30:27','2026-05-27 22:30:27',2);
INSERT INTO "posts" VALUES (30,'Hannah Crooks','hannah-crooks','Officiis nam aut quia voluptatibus voluptas. Vero cum culpa voluptatem porro. Doloribus labore laudantium aliquid quos officia. Voluptas dignissimos modi non quidem. Voluptatem quisquam perferendis non eaque.','Et molestiae a voluptatum veniam. Molestiae consequatur laboriosam dolor nam numquam occaecati rerum. Totam recusandae aut et cupiditate. Quia esse temporibus rem esse porro. Velit voluptatem voluptas velit animi. Sapiente rerum dicta sunt expedita officia. Laudantium dicta illo ex ipsum ut distinctio ea adipisci. Incidunt illo ut ad corrupti aspernatur nulla. Enim mollitia enim consequatur cumque. Quia est autem et et consectetur velit. Tenetur commodi reprehenderit quidem et. Sit totam pariatur id quis voluptatum ducimus ut. Laboriosam accusantium et ut qui deserunt molestiae. Voluptatem dolore suscipit minus ut officiis ut sed. Aut nihil et cumque dolorem sit.','https://via.placeholder.com/640x480.png/0066dd?text=officiis','not','2026-05-27 22:30:27','2026-05-27 22:30:27',2);
INSERT INTO "sessions" VALUES ('2CL3vR7saiqOqcKxtysbBpsvFAzcXSaapf2U0wnb',1,'127.0.0.1','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36 Edg/148.0.0.0','eyJfdG9rZW4iOiJqdHBQb2FyZ21JWlhLQXpSNVRVODlFZFdVMzYzWlZrV1BwdVU2YVZOIiwidXJsIjpbXSwiX3ByZXZpb3VzIjp7InVybCI6Imh0dHA6XC9cL3ByaW1lcnByb3llY3RvLnRlc3RcL2Jsb2dcL2RldGFpbFwvNSIsInJvdXRlIjoiYmxvZy5zaG93In0sIl9mbGFzaCI6eyJvbGQiOltdLCJuZXciOltdfSwibG9naW5fd2ViXzU5YmEzNmFkZGMyYjJmOTQwMTU4MGYwMTRjN2Y1OGVhNGUzMDk4OWQiOjF9',1779835554);
INSERT INTO "sessions" VALUES ('ffT5ZYNHtUeA4QJbsg6HT8XDZeCq8cCrCS3Gso6D',1,'127.0.0.1','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36 Edg/148.0.0.0','eyJfdG9rZW4iOiJ0dlZyVGllQktBenU1ZmN5OGtIZDdMZ254dnZRZDZmU1RTZms4MDZkIiwidXJsIjpbXSwiX3ByZXZpb3VzIjp7InVybCI6Imh0dHA6XC9cL3ByaW1lcnByb3llY3RvLnRlc3RcL2Jsb2c/cGFnZT0xIiwicm91dGUiOiJibG9nLmluZGV4In0sIl9mbGFzaCI6eyJvbGQiOltdLCJuZXciOltdfSwibG9naW5fd2ViXzU5YmEzNmFkZGMyYjJmOTQwMTU4MGYwMTRjN2Y1OGVhNGUzMDk4OWQiOjF9',1779854792);
INSERT INTO "sessions" VALUES ('2hrRoGGHhI6p5Zu136h7MAG5TFwz4XI9pyaO5ZYl',NULL,'127.0.0.1','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Herd/1.28.0 Chrome/120.0.6099.291 Electron/28.2.5 Safari/537.36','eyJfdG9rZW4iOiJKdmhDM09IbVdyRjM5WllodzRIR1Q2dmNsQ2h3RE1aeWI4MVNmWGM2IiwiX3ByZXZpb3VzIjp7InVybCI6Imh0dHA6XC9cL3ByaW1lcnByb3llY3RvLnRlc3RcLz9oZXJkPXByZXZpZXciLCJyb3V0ZSI6bnVsbH0sIl9mbGFzaCI6eyJvbGQiOltdLCJuZXciOltdfX0=',1779858157);
INSERT INTO "sessions" VALUES ('WwBnLh7O71GB5ZT1MJneqlNJTIecLouO0blBOHfm',NULL,'127.0.0.1','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Herd/1.28.0 Chrome/120.0.6099.291 Electron/28.2.5 Safari/537.36','eyJfdG9rZW4iOiJhVHRVcTVPT25iT1g0SnVEbkxBQlNKMFA4czNFaG9GTmdsWExDb1BYIiwiX3ByZXZpb3VzIjp7InVybCI6Imh0dHA6XC9cL3ByaW1lcnByb3llY3RvLnRlc3RcLz9oZXJkPXByZXZpZXciLCJyb3V0ZSI6bnVsbH0sIl9mbGFzaCI6eyJvbGQiOltdLCJuZXciOltdfX0=',1779893439);
INSERT INTO "sessions" VALUES ('1Zst76KUkqeo5jrSB7pe47lq7iCa4sxepxoKSX6f',NULL,'127.0.0.1','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Herd/1.28.0 Chrome/120.0.6099.291 Electron/28.2.5 Safari/537.36','eyJfdG9rZW4iOiJld28wMThGbFZXcWxya0g5bTVOMmlPME12RkRCa041enpOYnNRNk1xIiwiX3ByZXZpb3VzIjp7InVybCI6Imh0dHA6XC9cL3ByaW1lcnByb3llY3RvLnRlc3RcLz9oZXJkPXByZXZpZXciLCJyb3V0ZSI6bnVsbH0sIl9mbGFzaCI6eyJvbGQiOltdLCJuZXciOltdfX0=',1779893444);
INSERT INTO "sessions" VALUES ('NnirKne2VGJbKCCHJkwIn918zVskXJOhXFuXTLi9',1,'127.0.0.1','Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36 Edg/148.0.0.0','eyJfdG9rZW4iOiJXTU9SdEw3TVRsbUREU09NQkdPdlFLRFJPeEdtNHJ0dVBYUHBnM0VmIiwiX3ByZXZpb3VzIjp7InVybCI6Imh0dHA6XC9cL3ByaW1lcnByb3llY3RvLnRlc3RcL2Jsb2dcL2RldGFpbFwvMSIsInJvdXRlIjoiYmxvZy5zaG93In0sIl9mbGFzaCI6eyJvbGQiOltdLCJuZXciOltdfSwidXJsIjpbXSwibG9naW5fd2ViXzU5YmEzNmFkZGMyYjJmOTQwMTU4MGYwMTRjN2Y1OGVhNGUzMDk4OWQiOjF9',1779908063);
INSERT INTO "users" VALUES (1,'santiago','santiago@gmail.com',NULL,'$2y$12$eYvDMBeSKXxjCvAtjfPdOuCJZc2EI.L7J6s9BBvLhIAQ97nhtvYg.',NULL,'2026-05-26 15:55:02','2026-05-26 15:55:02');
CREATE INDEX IF NOT EXISTS "cache_expiration_index" ON "cache" (
	"expiration"
);
CREATE INDEX IF NOT EXISTS "cache_locks_expiration_index" ON "cache_locks" (
	"expiration"
);
CREATE INDEX IF NOT EXISTS "failed_jobs_connection_queue_failed_at_index" ON "failed_jobs" (
	"connection",
	"queue",
	"failed_at"
);
CREATE UNIQUE INDEX IF NOT EXISTS "failed_jobs_uuid_unique" ON "failed_jobs" (
	"uuid"
);
CREATE INDEX IF NOT EXISTS "jobs_queue_index" ON "jobs" (
	"queue"
);
CREATE INDEX IF NOT EXISTS "sessions_last_activity_index" ON "sessions" (
	"last_activity"
);
CREATE INDEX IF NOT EXISTS "sessions_user_id_index" ON "sessions" (
	"user_id"
);
CREATE UNIQUE INDEX IF NOT EXISTS "users_email_unique" ON "users" (
	"email"
);
COMMIT;
